### All notes
GET http://localhost:3001/api/notes

### One note(replace ID with a real one from MongoDB)
GET http://localhost:3001/api/notes/68d6d3e300790cafff7f82d6

### Create
POST http://localhost:3001/api/notes
Content-Type: application/json

{
  "content": "Testing new note via HTTP file",
  "important": true
}

### Update a note
PUT http://localhost:3001/api/notes/68d6d3e300790cafff7f82d6
Content-Type: application/json

{
  "content": "Updated note content",
  "important": false
}

### Delete
DELETE http://localhost:3001/api/notes/68d6d3e300790cafff7f82d6
